version: '3'

services:
  yolov8_training:
    container_name: yolov8_training
    build: ./
    image: yolov8_training:v2
    volumes:
      - ../:/code/
      # - ../datasets:/datasets
      - ../:/data/

    ipc: host
    mem_limit: '85g'
    memswap_limit: 85g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    command: tail -F anything
